/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;
import javax.swing.JTable;
import model.UserList;
import view.intern.adminnav.view_NewAdminForm;
import view.intern.adminnav.view_NewGameForm;
import view.intern.adminnav.view_NewUserForm;
import view.intern.adminnav.view_ShowUsers;

/**
 *
 * @author victo
 */
public class view_Navigation extends javax.swing.JFrame {

    /**
     * Creates new form view_Navigation
     */
    public view_Navigation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPanel = new javax.swing.JDesktopPane();
        jMenuBar2 = new javax.swing.JMenuBar();
        menuNew = new javax.swing.JMenu();
        menuNewAdmin = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        menuNewUser = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menuNewGame = new javax.swing.JMenuItem();
        menuShowUsers = new javax.swing.JMenu();
        menuShowGames = new javax.swing.JMenu();
        menuEdit = new javax.swing.JMenu();
        menuDelete = new javax.swing.JMenu();
        menuPerfil = new javax.swing.JMenu();
        menuLogout = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout desktopPanelLayout = new javax.swing.GroupLayout(desktopPanel);
        desktopPanel.setLayout(desktopPanelLayout);
        desktopPanelLayout.setHorizontalGroup(
            desktopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        desktopPanelLayout.setVerticalGroup(
            desktopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        getContentPane().add(desktopPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 590));

        jMenuBar2.setBackground(new java.awt.Color(240, 240, 240));
        jMenuBar2.setForeground(new java.awt.Color(0, 0, 0));
        jMenuBar2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        menuNew.setBackground(new java.awt.Color(204, 204, 204));
        menuNew.setForeground(new java.awt.Color(51, 51, 51));
        menuNew.setText("New");
        menuNew.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        menuNewAdmin.setBackground(new java.awt.Color(240, 240, 240));
        menuNewAdmin.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        menuNewAdmin.setForeground(new java.awt.Color(51, 51, 51));
        menuNewAdmin.setText("Admin");
        menuNewAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNewAdminActionPerformed(evt);
            }
        });
        menuNew.add(menuNewAdmin);
        menuNew.add(jSeparator4);

        menuNewUser.setBackground(new java.awt.Color(240, 240, 240));
        menuNewUser.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        menuNewUser.setForeground(new java.awt.Color(51, 51, 51));
        menuNewUser.setText("User");
        menuNewUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNewUserActionPerformed(evt);
            }
        });
        menuNew.add(menuNewUser);
        menuNew.add(jSeparator2);

        menuNewGame.setBackground(new java.awt.Color(240, 240, 240));
        menuNewGame.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        menuNewGame.setForeground(new java.awt.Color(51, 51, 51));
        menuNewGame.setText("Game");
        menuNewGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNewGameActionPerformed(evt);
            }
        });
        menuNew.add(menuNewGame);

        jMenuBar2.add(menuNew);

        menuShowUsers.setBackground(new java.awt.Color(204, 204, 204));
        menuShowUsers.setForeground(new java.awt.Color(51, 51, 51));
        menuShowUsers.setText("Show Users");
        menuShowUsers.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menuShowUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuShowUsersMouseClicked(evt);
            }
        });
        jMenuBar2.add(menuShowUsers);

        menuShowGames.setBackground(new java.awt.Color(204, 204, 204));
        menuShowGames.setForeground(new java.awt.Color(51, 51, 51));
        menuShowGames.setText("Show Games");
        menuShowGames.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuBar2.add(menuShowGames);

        menuEdit.setBackground(new java.awt.Color(204, 204, 204));
        menuEdit.setForeground(new java.awt.Color(51, 51, 51));
        menuEdit.setText("Edit");
        menuEdit.setEnabled(false);
        menuEdit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuBar2.add(menuEdit);

        menuDelete.setBackground(new java.awt.Color(204, 204, 204));
        menuDelete.setForeground(new java.awt.Color(51, 51, 51));
        menuDelete.setText("Delete");
        menuDelete.setEnabled(false);
        menuDelete.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menuDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuDeleteMouseClicked(evt);
            }
        });
        jMenuBar2.add(menuDelete);

        menuPerfil.setBackground(new java.awt.Color(204, 204, 204));
        menuPerfil.setForeground(new java.awt.Color(51, 51, 51));
        menuPerfil.setText("Perfil");
        menuPerfil.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuBar2.add(menuPerfil);

        menuLogout.setBackground(new java.awt.Color(204, 204, 204));
        menuLogout.setForeground(new java.awt.Color(51, 51, 51));
        menuLogout.setText("Log Out");
        menuLogout.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menuLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuLogoutMouseClicked(evt);
            }
        });
        menuLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLogoutActionPerformed(evt);
            }
        });
        jMenuBar2.add(menuLogout);

        setJMenuBar(jMenuBar2);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLogoutActionPerformed
        dispose();
    }//GEN-LAST:event_menuLogoutActionPerformed

    private void menuLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLogoutMouseClicked
        dispose();
    }//GEN-LAST:event_menuLogoutMouseClicked

    private void menuNewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNewUserActionPerformed
        view_NewUserForm newUserForm = new view_NewUserForm();
        desktopPanel.add(newUserForm);
        newUserForm.setVisible(true);
    }//GEN-LAST:event_menuNewUserActionPerformed

    private void menuNewAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNewAdminActionPerformed
        view_NewAdminForm newAdminForm = new view_NewAdminForm();
        desktopPanel.add(newAdminForm);
        newAdminForm.setVisible(true);
    }//GEN-LAST:event_menuNewAdminActionPerformed

    private void menuNewGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNewGameActionPerformed
        view_NewGameForm newGameForm = new view_NewGameForm();
        desktopPanel.add(newGameForm);
        newGameForm.setVisible(true);
    }//GEN-LAST:event_menuNewGameActionPerformed

    private void menuShowUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuShowUsersMouseClicked
        ShowUsers();
    }//GEN-LAST:event_menuShowUsersMouseClicked

    private void menuDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuDeleteMouseClicked
        DeleteUser();
    }//GEN-LAST:event_menuDeleteMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(view_Navigation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(view_Navigation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(view_Navigation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(view_Navigation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new view_Navigation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPanel;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JMenu menuDelete;
    private javax.swing.JMenu menuEdit;
    private javax.swing.JMenu menuLogout;
    private javax.swing.JMenu menuNew;
    private javax.swing.JMenuItem menuNewAdmin;
    private javax.swing.JMenuItem menuNewGame;
    private javax.swing.JMenuItem menuNewUser;
    private javax.swing.JMenu menuPerfil;
    private javax.swing.JMenu menuShowGames;
    private javax.swing.JMenu menuShowUsers;
    // End of variables declaration//GEN-END:variables

    public void EnableButtons(boolean state)
    {
        menuEdit.setEnabled(state);
        menuDelete.setEnabled(state);
    }
    
    view_ShowUsers showUsers;
    public void ShowUsers()
    {
        showUsers = new view_ShowUsers();
        showUsers.SetNavigation(this);
        
        desktopPanel.add(showUsers);
        showUsers.setVisible(true);
        
        EnableButtons(true);
    }
    
    public JTable userTable;
    public void DeleteUser()
    { 
        showUsers.SetUserTable();
        
        int pos = userTable.getSelectedRow();
        
        if (pos < 0)
        {
            JOptionPane.showMessageDialog(null, "Select a user.");
            return;
        }
        
        UserList.getUserList().remove(pos);
        showUsers.ReloadUserTable();
    }
}
