/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view.intern.adminnav;

import java.util.Arrays;
import javax.swing.JOptionPane;
import model.User;
import model.UserList;

/**
 *
 * @author victo
 */
public class view_NewUserForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form view_NewUserForm
     */
    public view_NewUserForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnCloseForm = new javax.swing.JLabel();
        btnAddAdmin = new javax.swing.JLabel();
        lblUsername1 = new javax.swing.JLabel();
        fldUsername = new javax.swing.JTextField();
        lblUsername2 = new javax.swing.JLabel();
        lblUsername3 = new javax.swing.JLabel();
        lblUsername4 = new javax.swing.JLabel();
        lblUsername5 = new javax.swing.JLabel();
        fldPhone = new javax.swing.JTextField();
        fldEmail = new javax.swing.JTextField();
        fldName = new javax.swing.JTextField();
        fldPassword = new javax.swing.JPasswordField();

        setTitle("New User");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCloseForm.setBackground(new java.awt.Color(102, 102, 102));
        btnCloseForm.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCloseForm.setForeground(new java.awt.Color(0, 0, 0));
        btnCloseForm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCloseForm.setText("CANCEL");
        btnCloseForm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCloseForm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseFormMouseClicked(evt);
            }
        });

        btnAddAdmin.setBackground(new java.awt.Color(102, 102, 102));
        btnAddAdmin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAddAdmin.setForeground(new java.awt.Color(0, 0, 0));
        btnAddAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAddAdmin.setText("SAVE");
        btnAddAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddAdminMouseClicked(evt);
            }
        });

        lblUsername1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblUsername1.setForeground(new java.awt.Color(0, 0, 0));
        lblUsername1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUsername1.setText("Name *");
        lblUsername1.setToolTipText("");

        fldUsername.setBackground(new java.awt.Color(240, 240, 240));
        fldUsername.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fldUsername.setForeground(new java.awt.Color(0, 0, 0));
        fldUsername.setMargin(new java.awt.Insets(2, 18, 2, 18));

        lblUsername2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblUsername2.setForeground(new java.awt.Color(0, 0, 0));
        lblUsername2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUsername2.setText("E-mail *");
        lblUsername2.setToolTipText("");

        lblUsername3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblUsername3.setForeground(new java.awt.Color(0, 0, 0));
        lblUsername3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUsername3.setText("Phone");
        lblUsername3.setToolTipText("");

        lblUsername4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblUsername4.setForeground(new java.awt.Color(0, 0, 0));
        lblUsername4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUsername4.setText("Username *");
        lblUsername4.setToolTipText("");

        lblUsername5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblUsername5.setForeground(new java.awt.Color(0, 0, 0));
        lblUsername5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUsername5.setText("Password *");
        lblUsername5.setToolTipText("");

        fldPhone.setBackground(new java.awt.Color(240, 240, 240));
        fldPhone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fldPhone.setForeground(new java.awt.Color(0, 0, 0));
        fldPhone.setMargin(new java.awt.Insets(2, 18, 2, 18));

        fldEmail.setBackground(new java.awt.Color(240, 240, 240));
        fldEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fldEmail.setForeground(new java.awt.Color(0, 0, 0));
        fldEmail.setMargin(new java.awt.Insets(2, 18, 2, 18));

        fldName.setBackground(new java.awt.Color(240, 240, 240));
        fldName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fldName.setForeground(new java.awt.Color(0, 0, 0));
        fldName.setMargin(new java.awt.Insets(2, 18, 2, 18));

        fldPassword.setBackground(new java.awt.Color(240, 240, 240));
        fldPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fldPassword.setForeground(new java.awt.Color(0, 0, 0));
        fldPassword.setMargin(new java.awt.Insets(2, 18, 2, 18));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblUsername1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fldName, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(28, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblUsername2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblUsername3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fldPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblUsername4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblUsername5, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fldPassword)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnAddAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCloseForm, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCloseForm, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fldName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fldPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 490, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseFormMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseFormMouseClicked
        dispose();
    }//GEN-LAST:event_btnCloseFormMouseClicked

    private void btnAddAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddAdminMouseClicked
        AddUser();
    }//GEN-LAST:event_btnAddAdminMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAddAdmin;
    private javax.swing.JLabel btnCloseForm;
    private javax.swing.JTextField fldEmail;
    private javax.swing.JTextField fldName;
    private javax.swing.JPasswordField fldPassword;
    private javax.swing.JTextField fldPhone;
    private javax.swing.JTextField fldUsername;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblUsername1;
    private javax.swing.JLabel lblUsername2;
    private javax.swing.JLabel lblUsername3;
    private javax.swing.JLabel lblUsername4;
    private javax.swing.JLabel lblUsername5;
    // End of variables declaration//GEN-END:variables

    String name, email, phone, username;
    char[] password;
    
    public void GetData()
    {
        name = fldName.getText();
        email = fldEmail.getText();
        phone = fldPhone.getText();
        username = fldUsername.getText();
        password = fldPassword.getPassword();
    }
    
    public void AddUser()
    {
        if (!Verify()) return;
        
        User newUser = new User(name, username, email, phone, password, false);
        UserList.addUser(newUser);
        
        JOptionPane.showMessageDialog(null, "Success!");
        
        fldName.setText("");
        fldUsername.setText("");
        fldEmail.setText("");
        fldPhone.setText("");
        fldPassword.setText("");
        
        dispose();
    }
    
    public boolean Verify()
    {
        GetData();
        
        if (name.isEmpty() || email.isEmpty() || username.isEmpty() || password.length <= 0)
        {
            JOptionPane.showMessageDialog(null, "Fill in all fields.");
            return false;
        }
        
        return true;
    }

}
