/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view.intern.adminnav;

import java.util.Arrays;
import javax.swing.JOptionPane;
import model.User;
import model.UserList;

/**
 *
 * @author victo
 */
public class view_NewAdminForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form view_NewAdminForm
     */
    public view_NewAdminForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCloseForm = new javax.swing.JLabel();
        fldUsername = new javax.swing.JTextField();
        lblUsername = new javax.swing.JLabel();
        lblUsername1 = new javax.swing.JLabel();
        fldPassword = new javax.swing.JPasswordField();
        btnAddAdmin = new javax.swing.JLabel();

        setTitle("New Admin");

        btnCloseForm.setBackground(new java.awt.Color(102, 102, 102));
        btnCloseForm.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCloseForm.setForeground(new java.awt.Color(0, 0, 0));
        btnCloseForm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCloseForm.setText("CANCEL");
        btnCloseForm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCloseForm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseFormMouseClicked(evt);
            }
        });

        fldUsername.setBackground(new java.awt.Color(240, 240, 240));
        fldUsername.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fldUsername.setForeground(new java.awt.Color(0, 0, 0));
        fldUsername.setMargin(new java.awt.Insets(2, 18, 2, 18));
        fldUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldUsernameActionPerformed(evt);
            }
        });

        lblUsername.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(0, 0, 0));
        lblUsername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsername.setText("Password *");
        lblUsername.setToolTipText("");

        lblUsername1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblUsername1.setForeground(new java.awt.Color(0, 0, 0));
        lblUsername1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsername1.setText("Username *");
        lblUsername1.setToolTipText("");

        fldPassword.setBackground(new java.awt.Color(240, 240, 240));
        fldPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fldPassword.setForeground(new java.awt.Color(0, 0, 0));
        fldPassword.setMargin(new java.awt.Insets(2, 18, 2, 18));

        btnAddAdmin.setBackground(new java.awt.Color(102, 102, 102));
        btnAddAdmin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAddAdmin.setForeground(new java.awt.Color(0, 0, 0));
        btnAddAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAddAdmin.setText("SAVE");
        btnAddAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddAdminMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAddAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCloseForm, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(fldUsername)
                    .addComponent(lblUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
                    .addComponent(fldPassword)
                    .addComponent(lblUsername1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCloseForm, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblUsername1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseFormMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseFormMouseClicked
        dispose();
    }//GEN-LAST:event_btnCloseFormMouseClicked

    private void btnAddAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddAdminMouseClicked
        AddAdmin();
    }//GEN-LAST:event_btnAddAdminMouseClicked

    private void fldUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldUsernameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAddAdmin;
    private javax.swing.JLabel btnCloseForm;
    private javax.swing.JPasswordField fldPassword;
    private javax.swing.JTextField fldUsername;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblUsername1;
    // End of variables declaration//GEN-END:variables

    String username;
    char[] password;
    
    public void GetData()
    {
        username = fldUsername.getText();
        password = fldPassword.getPassword();
    }
    
    public void AddAdmin()
    {
        if (!Verify()) return;
        
        User newUser = new User(fldUsername.getText(), fldPassword.getPassword(), true);
        UserList.addUser(newUser);
        
        JOptionPane.showMessageDialog(null, "Success!");
        
        dispose();
    }
    
    public boolean Verify()
    {
        GetData();
        
        if (username.isEmpty() || password.length <= 0)
        {
            JOptionPane.showMessageDialog(null, "Fill in all fields.");
            return false;
        }
        
        return true;
    }

}
