/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view.intern.adminnav;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.User;
import model.UserList;
import view.view_Navigation;

/**
 *
 * @author victo
 */
public class view_ShowUsers extends javax.swing.JInternalFrame {

    /**
     * Creates new form view_ShowUsers
     */
    public view_ShowUsers() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCloseTable = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsers = new javax.swing.JTable();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCloseTable.setBackground(new java.awt.Color(102, 102, 102));
        btnCloseTable.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCloseTable.setForeground(new java.awt.Color(0, 0, 0));
        btnCloseTable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCloseTable.setText("CANCEL");
        btnCloseTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCloseTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseTableMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCloseTable, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnCloseTable, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 390, 40));

        jScrollPane1.setFocusable(false);
        jScrollPane1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        String[] cols = {"ID", "Username", "Admin?"};
        DefaultTableModel model = new DefaultTableModel(cols, 0);

        List<User> list = UserList.getUserList();
        for (int i = 0; i < list.size(); i++)
        {
            User user = list.get(i);

            String admin;
            if (user.isAdmin()) admin = "Yes";
            else admin = "No";

            String[] row = {
                Integer.toString(user.getId()),
                user.getUserName(),
                admin
            };
            model.addRow(row);
        }
        tblUsers.setModel(model);
        jScrollPane1.setViewportView(tblUsers);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 370, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseTableMouseClicked
        dispose();
        navigationView.EnableButtons(false);
    }//GEN-LAST:event_btnCloseTableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnCloseTable;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUsers;
    // End of variables declaration//GEN-END:variables

    public void SetUserTable()
    {
        navigationView.userTable = tblUsers;
    }
    
    public void ReloadUserTable()
    {
        String[] cols = {"ID", "Username", "Admin?"};
        DefaultTableModel model = new DefaultTableModel(cols, 0);

        List<User> list = UserList.getUserList();
        for (int i = 0; i < list.size(); i++)
        {
            User user = list.get(i);

            String admin;
            if (user.isAdmin()) admin = "Yes";
            else admin = "No";

            String[] row = {
                Integer.toString(user.getId()),
                user.getUserName(),
                admin
            };
            
            model.addRow(row);
        }
        
        tblUsers.setModel(model);
    }
    
    view_Navigation navigationView;
    public void SetNavigation(view_Navigation nav)
    {
        navigationView = nav;
    }
}
